import { Router } from "express";
import prisma from "../../db.js";

const router = Router();

// GET all designs
router.get("/designs", async (req, res) => {
  try {
    const designs = await prisma.databaseDesign.findMany({
      orderBy: { updatedAt: "desc" },
    });
    res.json(designs);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// GET single design
router.get("/designs/:id", async (req, res) => {
  try {
    const design = await prisma.databaseDesign.findUnique({
      where: { id: parseInt(req.params.id) },
    });
    if (!design) return res.status(404).json({ error: "Design not found" });
    res.json(design);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// CREATE new design
router.post("/designs", async (req, res) => {
  const { name, canvasData, dbType, projectId } = req.body;
  try {
    const design = await prisma.databaseDesign.create({
      data: {
        name: name || "Untitled Schema",
        canvasData: canvasData || "{}",
        dbType: dbType || "postgresql",
        projectId: projectId ? parseInt(projectId) : null,
      },
    });
    res.status(201).json(design);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// UPDATE design
router.put("/designs/:id", async (req, res) => {
  const { name, canvasData, generatedScript, dbType } = req.body;
  try {
    const design = await prisma.databaseDesign.update({
      where: { id: parseInt(req.params.id) },
      data: {
        name,
        canvasData,
        generatedScript,
        dbType,
      },
    });
    res.json(design);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// DELETE design
router.delete("/designs/:id", async (req, res) => {
  try {
    await prisma.databaseDesign.delete({
      where: { id: parseInt(req.params.id) },
    });
    res.json({ message: "Design deleted successfully" });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// EXPORT script generator (mock generation logic for demo)
router.post("/designs/:id/export", async (req, res) => {
  try {
    const design = await prisma.databaseDesign.findUnique({
      where: { id: parseInt(req.params.id) },
    });
    if (!design) return res.status(404).json({ error: "Design not found" });

    // Mock script export generation logic based on DB type
    let script = "";
    const parsedData = JSON.parse(design.canvasData);
    const tables = parsedData.tables || [];

    if (design.dbType === "postgresql" || design.dbType === "mysql") {
      script = "-- Generated by Visual Database Designer\n\n";
      for (const table of tables) {
        script += `CREATE TABLE ${table.name} (\n`;
        const columns = table.columns || [];
        const colsSql = columns.map((col: any) => {
          let line = `  ${col.name} ${col.type}`;
          if (col.isPrimaryKey) line += " PRIMARY KEY";
          if (col.isNullable === false) line += " NOT NULL";
          return line;
        });
        script += colsSql.join(",\n");
        script += "\n);\n\n";
      }
    } else if (design.dbType === "mongodb") {
      script = "// Generated MongoDB Mongoose Schemas\n\n";
      for (const table of tables) {
        script += `const ${table.name}Schema = new mongoose.Schema({\n`;
        const columns = table.columns || [];
        const colsMongo = columns.map((col: any) => {
          return `  ${col.name}: { type: ${col.type === "Int" ? "Number" : "String"}, required: ${col.isNullable === false} }`;
        });
        script += colsMongo.join(",\n");
        script += "\n});\n\n";
      }
    }

    // Save generated script in DB
    const updated = await prisma.databaseDesign.update({
      where: { id: design.id },
      data: { generatedScript: script },
    });

    res.json({ script, design: updated });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

export default router;
